import { Card, DomNode, el, msg } from "gaia-commons-ts";

export default class Intro extends DomNode {

    constructor(lang: string) {
        super(".intro-view");
        this.append(
            el("header",
                el("video", { autoplay: true, muted: true, loop: true },
                    el("source", { src: "https://storage.googleapis.com/gaiaprotocol/banner.mp4", type: "video/mp4" }),
                ),
                el("main",
                    el("h1", "Gaia Protocol"),
                    el("p", msg("intro-view-intro", lang)),
                ),
            ),
            el("section.assets",
                el("main",
                    el("h2", msg("intro-view-assets-title", lang)),
                    el("p", msg("intro-view-assets-description", lang)),
                    el(".cards",
                        new Card({},
                            el("h3", "Gaia Token"),
                            el("p", msg("ingro-view-gaiatoken-description", lang)),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                        new Card({},
                            el("h3", "Gaia Protocol Gods"),
                            el("p"),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                    ),
                ),
            ),
            el("section.technologies",
                el("main",
                    el("h2", msg("intro-view-assets-title", lang)),
                    el("p", msg("intro-view-assets-description", lang)),
                    el(".cards",
                        new Card({},
                            el("h3", "Gaia Token"),
                            el("p", msg("ingro-view-gaiatoken-description", lang)),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                        new Card({},
                            el("h3", "Gaia Protocol Gods"),
                            el("p"),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                    ),
                ),
            ),
            el("section.services",
                el("main",
                    el("h2", msg("intro-view-assets-title", lang)),
                    el("p", msg("intro-view-assets-description", lang)),
                    el(".cards",
                        new Card({},
                            el("h3", "Gaia Token"),
                            el("p", msg("ingro-view-gaiatoken-description", lang)),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                        new Card({},
                            el("h3", "Gaia Protocol Gods"),
                            el("p"),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                    ),
                ),
            ),
            el("section.contents",
                el("main",
                    el("h2", msg("intro-view-assets-title", lang)),
                    el("p", msg("intro-view-assets-description", lang)),
                    el(".cards",
                        new Card({},
                            el("h3", "Gaia Token"),
                            el("p", msg("ingro-view-gaiatoken-description", lang)),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                        new Card({},
                            el("h3", "Gaia Protocol Gods"),
                            el("p"),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                    ),
                ),
            ),
            el("section.family-projects",
                el("main",
                    el("h2", msg("intro-view-assets-title", lang)),
                    el("p", msg("intro-view-assets-description", lang)),
                    el(".cards",
                        new Card({},
                            el("h3", "Gaia Token"),
                            el("p", msg("ingro-view-gaiatoken-description", lang)),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                        new Card({},
                            el("h3", "Gaia Protocol Gods"),
                            el("p"),
                            el("a",
                                msg("learn-more-button", lang),
                                el("i.fa-solid.fa-chevron-right"),
                            ),
                        ),
                    ),
                ),
            ),
        );
    }
}
